OpenSourcePolitics/decidim-tou

app/commands/decidim/participatory_processes/admin/create_participatory_process.rb, app/commands/decidim/participatory_processes/admin/update_participatory_process.rb, app/forms/decidim/participatory_processes/admin/participatory_process_form.rb, app/views/decidim/participatory_processes/admin/participatory_processes/_form.html.erb, config/i18n-tasks.yml, spec/commands/create_participatory_process_spec.rb
Add the address field in PP monkey patch
`address` field is missing because of monkey patchs in app that override PP views from interactive map.
=> Fix missing address field in pp

db/migrate/20201126165641_move_proposals_fields_to_i18n.decidim_proposals.rb
A migration has been run twice and created a nested hash in Proposal titles and bodies in Database. 
-  [x] Disable this migration to avoid running on production mode
Command to run in Dev environment : 
```
Decidim::Proposals::Proposal.all.each do |prop|
if prop.title["fr"].is_a? Hash
prop.title = prop.title["fr"]
end
if prop.body["fr"].is_a? Hash
prop.body = prop.body["fr"]
end
prop.save! if prop.has_changes_to_save?
end
```
=> Fix migration proposals

app/views/decidim/account/show.html.erb, spec/system/account_spec.rb
Hello ! 
Here's a PR to correct the fact that if we had only one locale, dropdown was still active -> Now he's disabled if we only have one and work properly if we have some more.
Another thing was to add some tests and to correct the bug of %{organization_name} interpretation that was not done. Now fixed and work also properly.
=> Fix - Account Language Selection || Fix language helper variable interpretation

Gemfile.lock, app/views/decidim/participatory_processes/participatory_processes/show.html.erb, spec/system/participatory_processes_spec.rb
Ensure assemblies are sort by `weight` rather than title in highlighted PP
=> [Fix] - assemblies order by weight in PP

app/controllers/decidim/assemblies/assemblies_controller.rb, spec/controllers/assemblies_controller_spec.rb
Hello ! I made a PR to fix a bug on assemblies concerning ordering of Participatory Processes related to it.
Now it follows this rule -> Firstly by ending date -> The later it ends, the more it will appear first
Then in this first order , order it by the starting date -> The earlier it was created,  the more it will appear first in this second ordering.
Hoping that will work properly, if you have any problem feel free to tell me about it.
=> Fix - Fixing order of PP's in assemblies

app/controllers/decidim/budgets/projects_controller.rb, spec/system/sorting_projects_spec.rb
When there are too much projects for one page, the reorder function does not work properly for the most voted.
This PR fixes the problem by changing reordering before paginating.
=> fix projects display

config/initializers/decidim_meetings.rb, spec/system/upcoming_meeting_for_card_view_hooks_spec.rb
🎩 Description
This PR remove the following bug : when a meeting unpublished is the next one for an assembly, it is displayed in the linked assembly card in the participatory process linked
📌 Related Issues
[Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=7606b488c3fc4986a954ab5cdf57ed33&p=c6701d2ccdfc4f2684fcabcf8c633faa&pm=c)
Testing
Describe the best way to test or validate your PR.
Example:
1. Link an assembly and a pp
2. Create a meeting closer to the others in the assembly
3. See it is not displayed in the pp page
=> fix unpublished meetings

OVERLOADS.md, app/forms/decidim/decidim_awesome/proposals/proposal_wizard_create_step_form_override.rb, app/validators/etiquette_validator.rb, spec/forms/proposal_wizard_create_step_form_spec.rb
This PR removes two validation concerning the creation of a proposal :
- The minimum length (previously 15, now none)
- The pourcentage of capital letters (previously <25%, now none)
This PR overrides an awesome file because the validation is defined in this file.
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=58e8880afd0a4183896ddfadc2db2bc9&pm=c)
Example:
- Go to the creation page of a proposal
- See there's no minimum length displayed
- Try creating a proposal with a title with less than 15 characters
- See it works
- Try creating a proposal with a title in full caps
- See it works
=> remove validations

Gemfile, Gemfile.lock, app/jobs/decidim/open_data_job.rb, config/sidekiq.yml, lib/extends/exporters/proposal_serializer.rb, spec/services/decidim/proposals/proposal_serializer_spec.rb
This PR is made to fix the OpenDataJob that was crashing if the author of a proposal was an organization because of the overriding of the serializer.
Related to [Notion](https://www.notion.so/opensourcepolitics/Toulouse-OpenDataJob-fails-and-blocks-exports-queue-f926e55a82e347eba4cd0dd5f29dce89?pvs=4)
- Fix Serializer
- Change queue of the job
- Add some specs
- Rewrite the cron to match the format of a normal cron task
- Bump Sidekiq to v7.0.7 (latest version)
=> [Fix] - OpenData Failing Job

app/views/decidim/participatory_processes/participatory_processes/_promoted_process.html.erb, app/views/decidim/participatory_processes/participatory_processes/show.html.erb, spec/commands/decidim/create_participatory_process_spec.rb, spec/commands/decidim/create_registration_spec.rb, spec/commands/decidim/update_participatory_process_spec.rb, spec/system/participatory_processes_spec.rb
This fixes the displaying of images into the participatory processes,
This also fixes every editor commands onto files to avoid bugs in the future but still related to this issue, just on different features.
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-bug-affichage-des-images-a9b20560941545378a113e9b4e9e37d4?pvs=4)
=> [Fix] - Participatory processes images not displayed

app/views/decidim/participatory_processes/participatory_processes/show.html.erb
Delete collapsible list for related processes, to fix the cards display. 
- Related to https://github.com/decidim/decidim/pull/10914/files?
- Fixes #?
Example:
* Link a process to other processes
* Change active phase of a related process to make it a long string
* See that the layout is not broken
Before
After
=> Fix related processes display

lib/extends/exporters/proposal_serializer.rb, spec/services/decidim/proposals/proposal_serializer_spec.rb
On proposals exports, the whole column "phone_number" is systematically empty. 
- Related to #118 
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Non-affichage-num-ro-tel-dans-exports-704979f01bac4022b54a289e1e3d0700?pvs=4)
Example:
* Activate Phone Authorization on proposal creation
* Create a proposal
* Export proposals
* See phone number in exports
If official proposal, should not export any phone number
=> fix: phone numbers not found in exports

app/commands/decidim/create_registration.rb, spec/commands/decidim/create_registration_spec.rb
`email_on_notification` is disabled by default and user does not receive welcome email. 
- Related to [Notion](https://www.notion.so/opensourcepolitics/Toulouse-Dev-notifications-inscription-c1501a00f48c4140bfe1629ddce34e58?pvs=4)
* Create a new account
* Go to letter opener (http://localhost:3000/letter_opener)
* Enter confirmation code 
* See received welcome message
=> fix: Add again email_on_notification

app/forms/decidim/registration_form.rb, app/views/decidim/devise/registrations/new.html.erb, spec/system/examples/registration_password_examples.rb
The purpose of this PR is to add again the newsletter's activation checkbox that was previously disabled.
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Dev-notifications-inscription-c1501a00f48c4140bfe1629ddce34e58?pvs=4)
Example:
* Register
* Check the newsletter checkbox
* Log as admin
* Send a newsletter
* Check if your new user has well received the newsletter
=> feat: Add newsletter to registration form

config/initializers/rack_attack.rb, lib/decidim_app/rack_attack.rb, spec/lib/decidim_app/rack_attack_spec.rb, spec/system/confirmation_spec.rb
Add configuration to disable completely rack attack using env var `ENABLE_RACK_ATTACK=0`
Now initializer logs the current Rack Attack configuration on startup
- Backport from [decidim-app#449](https://github.com/OpenSourcePolitics/decidim-app/pull/449)
=> fix: Rack attack can't be completely disabled

app/packs/src/decidim/user_registrations.js, spec/system/examples/registration_hide_nickname_examples.rb, spec/system/examples/registration_password_examples.rb, spec/system/registration_spec.rb
Previously added, the newsletter was working pretty well, but a feature that was important, the appearance of a modal as a reminder to check the newsletter wasn't appearing. This PR fixes that and add some tests about it.
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Recette-0-26-65907162f74c4f60ba59af419312e2b8?pvs=4)
Example:
* Try to Register
* Don't check the newsletter
* Fill in other fields
* See the appearance of the modal
* Proceed to register afterwards and check that there is no issue
=> fix: Add newsletter modal to the register page

app/controllers/decidim/assemblies/assemblies_controller.rb, spec/controllers/assemblies_controller_spec.rb
As a user, I expect related processes to be ordered by start date in assemblies show. 
- Related to backport of : #50 
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Mont-e-de-version-0-27-3cb7e71e74c246f4a65bec7f980208ce?pvs=4)
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Order-of-related-processes-in-assemblies-show-61390f84fe734d65b76fbe4638583f73?pvs=4)
=> feat: backport related processes sort

Gemfile, Gemfile.lock, config/initializers/friendly_signup.rb, spec/commands/decidim/create_registration_spec.rb
Allow to configure `notifications_sending_frequency` with ENV var `NOTIFICATIONS_SENDING_FREQUENCY` 
- Related to https://github.com/OpenSourcePolitics/decidim-module-extra_user_fields/pull/1
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-0-27-Param-trer-le-digest-notification-sur-Jamais-f46c952bab0b4c8886e3d1b5e6b6dbff?pvs=4)
Example:
* Run server with env var : `NOTIFICATIONS_SENDING_FREQUENCY=none bundle exec rails s`
* Create registration
* Login and check "My account"
=> feat: Allow to configure notifications_sending_frequency

app/controllers/decidim/assemblies/assemblies_controller.rb, app/helpers/decidim/assemblies/assemblies_helper.rb, config/locales/en.yml, config/locales/fr.yml, spec/controllers/assemblies_controller_spec.rb
This pull request backport a change that was made on 0.26 about sorting processes that are linked to assemblies onto the assemblies page.
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Mont-e-de-version-0-27-3cb7e71e74c246f4a65bec7f980208ce?pvs=4)
Example:
* Create few processes , past active and future.
* Go to assemblies and select one
* Link new processes to the assemblies
* Access assemblies page in the front office
* Check that everything has been well sorted
=> feature: Sort processes linked to assemblies

.env-example, .github/workflows/ci_cd.yml, Gemfile, Gemfile.lock, app/views/decidim/account/show.html.erb, config/i18n-tasks.yml, spec/commands/decidim/create_registration_spec.rb, spec/lib/decidim_app/k8s/organization_exporter_spec.rb, spec/system/account_spec.rb, spec/system/extra_user_fields/account_spec.rb
This PR backports a feature that was previously on Toulouse but that we removed before backporting it onto decidim-app
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-0-27-Backport-language-selector-from-decidim-app-f8b9255b4dc94d788e2ac9ca8de1c8f6?pvs=4)
* Go to the file `config/initializers/decidim.rb``
* Change line 16 and paste this 
`config.available_locales = ENV.fetch("AVAILABLE_LOCALES", "en").split(",").map(&:to_sym)`
* Start your server using `NOTIFICATIONS_SENDING_FREQUENCY=weekly bundle exec rails s`
* Verify that you have no more language selector
* Create a new user
* Check in its profile that the notifications settings are well set to weekly …
=> backport: Language selector and selection of notification sending frequency

config/initializers/half_signup.rb
Disabling tos page after signup to match the request of Toulouse
=> fix: disable tos page after signup

db/migrate/20240419095228_modify_notification_frequency_for_decidim_users.rb
🚨  Create a migration to set Notification frequency to `none` for **all users in the database**. 
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Recette-1-b8a712260fe74836a9a8836c2cfaa3cc?pvs=4)
=> fix: Set Notification Frequency migration for Decidim users

lib/tasks/decidim_app.rake
Rescue `StandardError` when migration fails and run `decidim:db:migrate`  instead
=> feat!: Rescue StandardError on migration fail

db/migrate/20240521130556_modify_decidim_users_registration_metadata.rb, db/schema.rb
Copy users `registration_metadata` to `extended_data` to make the extra user fields and customizations compatible.
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Migration-sign-up-form-5f9ddaa297f14f3fa2a70ff985fb4e31?pvs=4)
```
```
🚨 **This PR modify data through Rails migration. Data should only be copied and a field `modified_at` is present on each record where `extended_data` has been updated**
=> feat: Migration to fix registration metadata

db/schema.rb, lib/tasks/repair_data.rake
In `extended_data` field on `Decidim::User`, birth date are formatted as follow : `2000-January-01`, this rake task will update each record as follow `2000-01-01`
`bundle exec rake decidim:repair:birth_date`
=> fix: Add Rake task to fix birth date

Gemfile.lock
Bump decidim-module-half_sign_up and decidim-module-ptp modules for corrected fr translations
- https://github.com/OpenSourcePolitics/decidim-module-half_sign_up/pull/32
- https://github.com/OpenSourcePolitics/decidim-module-ptp/pull/7
- https://github.com/OpenSourcePolitics/decidim-module-ptp/pull/8
- https://github.com/OpenSourcePolitics/decidim-module-ptp/pull/9
=> fix(i18n): bump modules for fr budget translations

Gemfile.lock
=> fix: Use current_order when reviewing vote in budget booth

Gemfile.lock
=> fix: Use current_order when reviewing vote in budget booth (#218)

config/routes.rb
Revert of the following commit https://github.com/OpenSourcePolitics/decidim-tou/commit/79154e4544aa4aa3f42724a8beabd4cfe04bbdf5 to reactive the OpenData route on decidim-tou. 
* Try to download the OpenData file 
⚠️ You might have to comment ou remove the `decidim-phone_authorization_handler` gem to test opendata locally with seeds
=> feat: Activate open data route

.github/workflows/ci_cd.yml, app/jobs/decidim/export_job.rb, config/initializers/extends.rb, lib/extends/lib/decidim/phone_authorization_handler/proposal_serializer_extend.rb, spec/jobs/export_job_spec.rb
This PR fixes the issue of not receiving infos from the author of a proposal when exporting as a user who's an administrator from a processes and not an administrator from the platform.
- [Toulouse & decidim-app - Non extraction des mails dans les exports de propositions pour les admins d’espace](https://www.notion.so/opensourcepolitics/Toulouse-decidim-app-Non-extraction-des-mails-dans-les-exports-de-propositions-pour-les-admins-d-2f782358512a4ff1a2e043d661677f99?pvs=4)
Example:
* Sign in as an admin 
* Go to a proposal component with published proposals
* Click on the export button
* See that you can view email and names of the participants
* Invite yourself as an admin …
=> fix: Export issue for Processes Administrators

Makefile, app/services/decidim/download_your_data_exporter.rb, config/application.rb, lib/decidim/seven_zip_wrapper.rb, lib/extends/comments/comment_serializer_extends.rb, lib/extends/comments/comment_vote_serializer_extends.rb, spec/services/decidim/download_your_data_exporter_spec.rb, spec/shared/has_questionnaire.rb, spec/spec_helper.rb
When I load my personal data, I receive an email with a zip file and a password to open it. The password is now functional, I can open the file and access my personal data.
- Related to issue https://github.com/decidim/decidim/issues/13037
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=54547f3ef83a4d1e806cdeee4a43cf60&pm=c)
- backport de https://github.com/decidim/decidim/pull/13185/files
After login, go to "My account"
Go to "My data"
Click on "Request data"
Go to you mail and download the zip file
Open the zip file and enter the password provided in the mail
See that you open the zip and access to your personal data file
=> Backport seven zip as cli wrapper
