app/assets/javascripts/decidim/user_registrations.js.es6
app/assets/stylesheets/decidim.scss
app/assets/stylesheets/decidim/modules/_horizontal-steps.scss
app/commands/decidim/create_registration.rb
app/controllers/decidim/devise/registrations_controller.rb
app/forms/decidim/registration_form.rb
app/views/decidim/devise/registrations/new.html.erb
app/views/decidim/devise/shared/_links.html.erb
app/views/decidim/devise/shared/_omniauth_buttons.html.erb
app/views/devise/mailer/invitation_instructions.html.erb
app/views/devise/mailer/invitation_instructions.text.erb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/secrets.yml
spec/commands/decidim/create_registration_spec.rb
spec/controllers/registrations_controller_spec.rb
spec/forms/registration_form_spec.rb
spec/system/decidim/authentication_spec.rb
spec/system/decidim/registration_spec.rb
spec/system/decidim/registration_unbundled_consent_spec.rb

Backport custom fields in registration form

Backport custom registration fields

---

app/commands/decidim/assemblies/admin/create_assembly.rb
app/commands/decidim/assemblies/admin/update_assembly.rb
app/forms/decidim/assemblies/admin/assembly_form.rb
app/models/decidim/assembly.rb
app/views/decidim/assemblies/admin/assemblies/_form.html.erb
app/views/decidim/assemblies/assemblies/show.html.erb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
spec/commands/decidim/create_assembly_spec.rb
spec/models/decidim/assembly_spec.rb

Backport sort child assemblies by title

Backport child assemblies sort

---

app/assets/stylesheets/decidim.scss
app/assets/stylesheets/decidim/modules/_horizontal-steps.scss
app/assets/stylesheets/decidim/modules/_signup.scss
app/commands/decidim/create_user_complete_registration.rb
app/controllers/decidim/devise/registrations_controller.rb
app/controllers/decidim/user_complete_registration_controller.rb
app/forms/decidim/registration_form.rb
app/forms/decidim/user_complete_registration_form.rb
app/views/decidim/devise/shared/_omniauth_buttons.html.erb
app/views/decidim/user_complete_registration/_areas.html.erb
app/views/decidim/user_complete_registration/_scopes.html.erb
app/views/decidim/user_complete_registration/show.html.erb
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/routes.rb
spec/commands/decidim/create_user_complete_registration_spec.rb
spec/forms/registration_form_spec.rb
spec/forms/user_complete_registration_form_spec.rb
spec/system/user_complete_registration_spec.rb

Fix : 
- CSS responsive
- Redirection to `user_complete_registration_path` after signing up
- Add birth date field mandatory

Fix registration form

---

app/assets/stylesheets/decidim.scss
config/locales/fr.yml

* Fix UI sign in form
* Translate french locales in sign in form
Before fix : 
After fix :

Fix user sign in form UI

---

Gemfile.lock

Bump - Fix map container

---

app/presenters/decidim/participatory_processes/participatory_process_presenter.rb
spec/serializers/decidim/participatory_processes/participatory_process_serializer_spec.rb

As an admin, when trying to export a participatory space JSON file, I don't receive the email.
Server error is due to an empty hero image url or banner image url.

Fix pp admin exporter

---

app/views/decidim/account/show.html.erb
config/i18n-tasks.yml
spec/system/decidim/account_spec.rb

Remove field from account form : 
- Personal url
- About me
- Avatar

Clear user account

---

app/views/layouts/decidim/_process_header_steps.html.erb
config/locales/en.yml
config/locales/fr.yml

This PR aims to fix the "View steps" button class when CTA steps button is enabled. 
Sorry @armandfardeau I forgot it in the specification!

Fix steps button when steps CTA enabled

---

app/assets/javascripts/decidim/user_registrations.js.es6
app/forms/decidim/registration_form.rb
spec/system/decidim/registration_spec.rb

refactor js registration form

---

app/serializers/decidim/debates/debate_serializer.rb
app/serializers/decidim/exporters/serializer.rb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
lib/extends/serializer/comment_serializer_extends.rb
lib/extends/serializer/user_answers_serializer_extends.rb
spec/serializers/comment_serializer_spec.rb
spec/serializers/debate_serializer_spec.rb
spec/serializers/decidim/exporters/serializer_spec.rb
spec/serializers/user_answer_serializer_spec.rb

Add a new column in the serializer.

Add age scope in exports

---

app/commands/decidim/create_registration.rb
spec/commands/decidim/create_registration_spec.rb
spec/system/authentication_spec.rb

Change default for email_on_notification

change email on notification

---

app/commands/decidim/participatory_processes/admin/create_participatory_process.rb
app/commands/decidim/participatory_processes/admin/update_participatory_process.rb
app/forms/decidim/participatory_processes/admin/participatory_process_form.rb
app/views/decidim/participatory_processes/admin/participatory_processes/_form.html.erb
spec/commands/decidim/create_participatory_process_spec.rb
spec/forms/participatory_process_form_spec.rb
spec/system/admin_manages_participatory_processes_spec.rb

added the changes between module files and toulouse files

Fix interactive maps

---

config/initializers/extends.rb
db/migrate/20220718142533_modify_emitter_in_participatory_processes.rb
lib/extends/serializer/user_answers_serializer_extends.rb
spec/commands/decidim/create_participatory_process_spec.rb
spec/serializers/decidim/forms/user_answers_serializer_spec.rb

This PR allows to export email and name of users in forms exporter

Add email / name to user answers form exporter

---

app/packs/stylesheets/decidim/decidim_application.scss
app/views/layouts/decidim/_wrapper.html.erb
db/migrate/20220718142533_modify_emitter_in_participatory_processes.rb
spec/commands/decidim/create_participatory_process_spec.rb

Add the organization name Next to the logo in the header
Add these lines below this block : 
```
.logo-wrapper span::before {
border-left: 4px solid var(--header_color);
}
```
Lines to add : 
```
.logo-wrapper span {
padding: .5rem !important;
}
```

Add organization name next to the logo

---

app/cells/decidim/participatory_processes/content_blocks/highlighted_processes/show.erb
app/cells/decidim/participatory_processes/process_group_m/header.erb
app/cells/decidim/participatory_processes/process_m/header.erb
db/migrate/20220718142533_modify_emitter_in_participatory_processes.rb
spec/commands/decidim/create_participatory_process_spec.rb
spec/system/participatory_processes_spec.rb

Add missing linked assemblies on cards

Add missing linked assemblies

---

app/forms/decidim/user_interest_scope_form.rb
app/forms/decidim/user_interests_form.rb
spec/forms/user_interest_scope_form_spec.rb
spec/forms/user_interests_form_spec.rb

Sort subscopes in user interests by alphanumeric order.

[Feature] - Sort user interests

---

app/cells/decidim/participatory_processes/content_blocks/highlighted_processes_cell.rb
app/cells/decidim/participatory_processes/process_group_m_cell.rb
app/helpers/application_helper.rb
app/models/decidim/participatory_process.rb
spec/cells/decidim/participatory_processes/content_blocks/highlighted_processes_cell_spec.rb
spec/models/decidim/participatory_process_spec.rb

Sort linked assemblies by title

Sort linked assemblies by title

---

app/helpers/decidim/check_boxes_tree_helper.rb
db/seeds.rb
spec/helpers/decidim/check_boxes_tree_helper_spec.rb

Sort scopes by alphanumeric order

[Fix] - Sort of checkboxes scopes

---

app/controllers/decidim/assemblies/assemblies_controller.rb

Sort related PP in assemblies by `start_date DESC`

Sort PP by start date

---

app/views/decidim/budgets/projects/_count.html.erb

Modify the number of projects when filtering

fix projects display

---

lib/decidim/dev/test/w3c_rspec_validators_overrides.rb
spec/spec_helper.rb

This PR fixes the failing tests, according to [this pr](https://github.com/decidim/decidim/pull/10020)

fix failing test

---

package-lock.json
package.json
yarn.lock

🎩 Description
This PR remove the following bug : when closing a meeting on the map, it makes the closed meetings appears.
It appears to be related to the leaflet version
📌 Related Issues
[Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=7606b488c3fc4986a954ab5cdf57ed33&p=757a63e1276b4849a29368cf09149450&pm=c)
Testing
Describe the best way to test or validate your PR.
Example:
1. Go to [localhost:3000//meetings/)
2. Click on a meeting and close it 
3. See the redirection to the passed meetings

fix close meetings

---

Gemfile
Gemfile.lock
db/migrate/20230425132228_add_warning_date_to_users.decidim_cleaner.rb
db/schema.rb

https://www.notion.so/opensourcepolitics/Toulouse-Bump-cleaner-4d7a117d024a4952ba605367f8b2849e?pvs=4

Bump cleaner

---

Gemfile
Gemfile.lock

Sidekiq is pinned to the wrong version

Pin sidekiq dependencies

---

.github/workflows/ci_cd.yml
app/views/decidim/participatory_processes/participatory_processes/_promoted_process.html.erb
app/views/decidim/participatory_processes/participatory_processes/show.html.erb
spec/commands/decidim/create_participatory_process_spec.rb
spec/commands/decidim/create_registration_spec.rb
spec/commands/decidim/update_participatory_process_spec.rb
spec/system/participatory_processes_spec.rb

* Transform the editor to editor_admin
* Fix linter small issues
* add test
* Update test#### :tophat: Description
- Fixes #?
Example:
* See ...

Bump master

---

config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml

Add missing locales in user signup form

Add missing locales

---

app/views/decidim/blogs/posts/_posts.html.erb
config/sidekiq.yml
lib/extends/exporters/proposal_serializer.rb
spec/factories.rb
spec/services/decidim/proposals/proposal_serializer_spec.rb
spec/system/explore_posts_spec.rb
spec/system/upcoming_meeting_for_card_view_hooks_spec.rb
yarn.lock

PR to merge on master the fixes #150 and #147 
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Recette-IH-ef758db211ae49da90645198d90983ed)
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Non-affichage-num-ro-tel-dans-exports-704979f01bac4022b54a289e1e3d0700)

release: Fix exports and recette 

---

config/initializers/extends.rb
lib/extends/commands/decidim/verifications/authorize_user_extends.rb
spec/commands/decidim/verifications/authorize_user_spec.rb

*Please describe your pull 
Admins receives verification conflicts emails, this PR disables Verification conflicts
Backport from https://github.com/OpenSourcePolitics/decidim-cese/pull/57

fix: Remove verification conflicts

---

app/commands/decidim/create_registration.rb
app/forms/decidim/registration_form.rb
app/packs/src/decidim/user_registrations.js
app/views/decidim/devise/registrations/new.html.erb
spec/commands/decidim/create_registration_spec.rb
spec/system/examples/registration_hide_nickname_examples.rb
spec/system/examples/registration_password_examples.rb
spec/system/registration_spec.rb

- `email_on_notification` is false by default
- Remove newsletter checkbox + modale

Bump master from Develop

---

Gemfile
Gemfile.lock
config/application.rb
yarn.lock

Downgrade `wicked_pdf` to 2.6.3
- Related to https://github.com/decidim/decidim/issues/12135
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Decidim-Forms-ExportQuestionnaireAnswersJob-failed-d25f9a9280884ad99928cf1e364652fb?pvs=4)
Example:
* Answer survey
* Export a single answer
* Email in letter_opener should be present with PDF

fix: Add wicked_pdf 2.6.3

---

app/controllers/decidim/assemblies/assemblies_controller.rb
app/controllers/decidim/participatory_processes/participatory_processes_controller.rb
db/seeds.rb

fix: Default order for PPs

---

Gemfile.lock

Bump Extra User Fields to latest commit
* Add underage field

bump: Extra user fields

---

Gemfile
Gemfile.lock
config/initializers/decidim.rb
config/initializers/half_signup.rb
db/migrate/20240404092252_create_auth_settings.decidim_half_signup.rb
db/migrate/20240404092253_add_phone_number_to_decidim_user.decidim_half_signup.rb
db/migrate/20240404092310_add_main_image_to_decidim_budgets_budgets.decidim_budgets_booth.rb
db/migrate/20240404092311_create_decidim_budgets_user_data.decidim_budgets_booth.rb
db/schema.rb
package-lock.json
yarn.lock

Addition of Half Signup and BudgetsBooth and bump EUF
- [Notion card 1](https://www.notion.so/opensourcepolitics/Toulouse-Ajout-half-sign-up-03f5a56aea724f95903b1b0c5484699a?pvs=4)
- [Notion card 2](https://www.notion.so/opensourcepolitics/Toulouse-Ajout-du-module-budget_booth-0-27-5833d68357624167b8df0b91042a1ea3?pvs=4)

feat: Addition of Half Signup and BudgetsBooth and bump EUF

---

Gemfile.lock

Bump to the newest version the module to fix some major issues that we encountered during the product revies
- [Notion card](https://www.notion.so/opensourcepolitics/Half-sign-up-Ajouter-FR-aa123c5560b846159521b97840a9811e?pvs=4)

bump: Bump half_signup to the newest version

---

app/services/decidim/repair_url_in_content_service.rb

fix: Fix failing test

---

config/initializers/extra_user_fields.rb
docker-compose.local.yml

Set `NOTIFICATIONS_SENDING_FREQUENCY` to none by default

fix: notifications sending frequency

---

config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml

Add missing locales from the active/past/future filters from linked processes onto assemblies
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Backport-ancre-de-navigation-from-decidim-tou-d6a4adb1835d40d090da799facff9f3b?pvs=4)
Example:
* Go to assemblies settings
* Link to an assembly the seeded processes that were made
* Access to assembly's front office
* Check that nothing is missing

fix: Add missing locales

---

app/services/decidim/sms_gateway_service.rb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml

Fix SMS translations keys
- Fixes #?
Example:
* See ...

fix: SMS message

---

Gemfile.lock

Bump module emitter
- Add CSS
- Update french translations
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Fixs-module-Emitter-2b09b34116a940c59239d862ce4c99d7?pvs=4)

fix: Bump module emitter

---

yarn.lock

Install yarn.lock dependencies

fix: Interactive map

---

Gemfile
Gemfile.lock
Makefile
app/services/decidim/sms_gateway_service.rb
config/environments/production.rb
config/initializers/half_signup.rb

Fix 422 and concurrency issue on vote
Environment variables : 
* `RAILS_LOG_LEVEL` default: `warn`
* `HALF_SIGNUP_SKIP_CSRF` default: `false`
🚨 Log level will change from `info` to `warn` by default.

fix: 422 on budget

---

Gemfile
Gemfile.lock
Makefile
app/commands/decidim/participatory_processes/admin/create_participatory_process.rb
app/commands/decidim/participatory_processes/admin/update_participatory_process.rb
app/forms/decidim/participatory_processes/admin/participatory_process_form.rb
app/services/decidim/sms_gateway_service.rb
config/environments/production.rb
config/initializers/decidim_emitter.rb
config/initializers/half_signup.rb
yarn.lock

- Fix 422 errors on budget vote
- Fix Scopes Geocoding
- Fix Participatory Process Address
* `RAILS_LOG_LEVEL` default: `warn`
* `HALF_SIGNUP_SKIP_CSRF` default: `false`

release 0.3.2

---

Gemfile
Gemfile.lock
spec/services/decidim/repair_nickname_service_spec.rb
spec/system/proposals_spec.rb

fix: Bump module half signup

---

Gemfile.lock

Revert fixes : 
https://github.com/OpenSourcePolitics/decidim-module-half_sign_up/pull/36/files
https://github.com/OpenSourcePolitics/decidim-module-half_sign_up/pull/39

revert: Downgrade Half Singup

---

Dockerfile.local
Makefile
docker-compose.local.yml

feat: Enhance local Docker build

---

.github/workflows/ci_cd.yml
app/packs/src/decidim/decidim_awesome/admin/custom_fields_builder.js
app/packs/src/decidim/decidim_awesome/forms/custom_fields_renderer.js
config/initializers/awesome_defaults.rb

This PR fixes multiple issues reported by Toulouse related to the GDPR 
- [Notion card](https://www.notion.so/opensourcepolitics/Toulouse-Decidim-app-00afcefbf5824f4c808d56ee1448af6b?pvs=4)
Example:
* Access to the local platform
* Open the network (right click + inspect + check on the right until you find "Network")
* Switch to French Language
* Filter using the search bar for "fr-FR"
* Refresh the page with the network open
* Make sure you see the fr-FR.lang and than when you click on it you see this url `https://decidim.storage.opensourcepolitics.eu/osp-cdn/form_builder/1.1.0` linked to the file
*Please add screenshots of the changes you're proposing if related to the …

fix: Replace all mentions of cdn.jsdelivr.net by our self-hosted cdn

---

Gemfile.lock

Bump module phone_authorization_handler to add address to proposals admin export
- [Odoo card](https://opensourcepolitics.odoo.com/web#id=2491&cids=1&menu_id=325&action=471&model=project.task&view_type=form)
1. As an admin, go to a process
2. Go to proposals and export proposals as excel for example
3. See that you have an address column with addresses of proposals

bump: phone_authorization_handler module

---

app/services/decidim/download_your_data_exporter.rb

Don't create temporary directory if already exist

fix: Download your data - already existing tmp directory case
